version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: appointment_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=appointmentdb 
      - DB_USER=appointment_user
      - DB_PASSWORD=appointment_password
      - SECRET_KEY=your_secret_key_here
      - PYTHONUNBUFFERED=1
      - PYTHONMALLOC=malloc
    volumes:
      - ./backend:/app
    command: sh -c "python create_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    mem_limit: 3g
    mem_reservation: 2g
    networks:
      - appointment_network

  llm_service:
    build: 
      context: ./llm_service
    container_name: llm_service
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - PYTHONMALLOC=malloc
    mem_limit: 1g
    mem_reservation: 512m
    networks:
      - appointment_network

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_DATABASE=appointmentdb
      - MYSQL_USER=appointment_user
      - MYSQL_PASSWORD=appointment_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    mem_limit: 1g
    networks:
      - appointment_network
    healthcheck:
      test: mysqladmin ping -h localhost -u appointment_user -pappointment_password
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: appointment_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    mem_limit: 2g
    mem_reservation: 1g
    networks:
      - appointment_network
    depends_on:
      - backend

networks:
  appointment_network:
    driver: bridge

volumes:
  mysql_data:
